feat: add currency test
dacadeorg/dacade-frontend-app pull request #1085
Opened 2024-03-04 14:51 UTC by Samantha-KY

# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [x] Tests have been added or updated to reflect your changes.
- [x] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

This PR add test for the currency component

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

:question:

## Issues Fixed

Enter the issue numbers resolved by this pull request below, if any.

1. :question:

## Other Relevant Information

Provide any other important details below.

2024-03-05 08:24 UTC, serapieTuyishime commented on __tests__/components/ui/Currency.test.tsx
The file needs formatting

2024-03-05 09:20 UTC, Jonath-z requested changes

2024-03-05 09:20 UTC, Jonath-z commented on __tests__/components/ui/Currency.test.tsx
> +    expect(currency).toBeInTheDocument();
This is already tested ... no need to repeat it again

2024-03-06 09:14 UTC, Jonath-z approved these changes

2024-03-06 11:54 UTC, serapieTuyishime approved these changes

2024-03-06 11:54 UTC, merged