feat: add certificate test
dacadeorg/dacade-frontend-app pull request #1089
Opened 2024-03-04 16:47 UTC by Samantha-KY

# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [x] Tests have been added or updated to reflect your changes.
- [x] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

This PR add test for certificate component

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

:question:

## Issues Fixed

Enter the issue numbers resolved by this pull request below, if any.

1. :question:

## Other Relevant Information

Provide any other important details below.

2024-03-05 09:25 UTC, Jonath-z requested changes

2024-03-06 09:22 UTC, Jonath-z requested changes

2024-03-06 09:22 UTC, Jonath-z commented on __tests__/components/ui/Certificate.test.tsx
> +jest.mock("@/icons/certificates/Sui.svg", () => "SuiIcon");
This is not right, it should already be mocked globally, if not yet, please apply a transformer, so we dont need to mock all the time we want to test a component with an SVG

2024-03-06 09:22 UTC, Jonath-z commented on __tests__/components/ui/Certificate.test.tsx
> +        expect(certificate).toBeInTheDocument();
This is tested already in the first test :)

2024-03-11 08:28 UTC, Jonath-z approved these changes

2024-03-11 09:56 UTC, serapieTuyishime approved these changes

2024-03-11 09:56 UTC, merged