feat: add badge test
dacadeorg/dacade-frontend-app pull request #1094
Opened 2024-03-05 13:39 UTC by Samantha-KY

# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [x] Tests have been added or updated to reflect your changes.
- [x] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

This PR add test for the badge component

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

:question:

## Issues Fixed

Enter the issue numbers resolved by this pull request below, if any.

1. :question:

## Other Relevant Information

Provide any other important details below.

2024-03-06 09:16 UTC, Jonath-z requested changes

2024-03-06 09:16 UTC, Jonath-z commented on __tests__/components/ui/Badge.test.tsx
Please, can you format this file?

2024-03-11 08:27 UTC, Jonath-z approved these changes

2024-03-11 09:54 UTC, serapieTuyishime approved these changes

2024-03-11 09:54 UTC, merged