fix: shorten numbers to K in rewards, bounties, challenge cards
dacadeorg/dacade-frontend-app pull request #1095
Opened 2024-03-06 10:15 UTC by serapieTuyishime

2024-03-06 13:56 UTC, Jonath-z commented on src/components/cards/community/_partials/RewardBadge.tsx
> +        {reward.amount} {reward.token}
why you don't  make the amount here short?

2024-03-06 15:47 UTC, mhenriette approved these changes

2024-03-11 14:50 UTC, Jonath-z approved these changes

2024-03-18 08:29 UTC, musayann requested changes

2024-03-21 10:30 UTC, musayann approved these changes

2024-03-21 10:30 UTC, merged