feat: add sidenavigation partial action test
dacadeorg/dacade-frontend-app pull request #1096
Opened 2024-03-06 12:51 UTC by Samantha-KY

# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [x] Tests have been added or updated to reflect your changes.
- [x] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

This PR adds test for the SideNavigation component

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

:question:

## Issues Fixed

Enter the issue numbers resolved by this pull request below, if any.

1. :question:

## Other Relevant Information

Provide any other important details below.

2024-03-14 09:46 UTC, Jonath-z requested changes
Consider also to format all the files please :)

2024-03-14 09:46 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +    );
Can you create a rendern function for this component, you can refer to the button tests

2024-03-14 09:46 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +    expect(link.children[0].className).toContain("activable-link");
let's avoid testing classes, the name of this call can change while the component is still behaving the same way.

2024-03-14 09:46 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Content.test.tsx
> +  });
This is hard to follow, let's avoid testing styles, the active style can change at anytime while the component still have the same behavour

2024-03-14 09:46 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/SideNavLink.test.tsx
Please format this file

2024-03-14 09:46 UTC, Jonath-z commented on src/components/ui/SideNavigation/_partials/Sub.tsx
> +      <Link data-testid="linkId" href={{ pathname: item.link, hash: subitem.link }} className={`relative text-gray-500 opacity-50 hover:opacity-100 ${!subitem.exact ? "activable-link" : ""}`}>
I wonder, don't we have this already tested? because if it's tested then we don't need to test it again.

2024-03-15 09:56 UTC, Jonath-z requested changes

2024-03-15 09:56 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/SubLink.test.tsx
Can you format this file please? Try to have prettier setup with your editor

2024-03-15 09:56 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/SubLink.test.tsx
> +        expect(link.firstChild?.textContent).toBe(subitem.label)
You can change the naming here, lable not link

2024-03-15 09:56 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Sub.test.tsx
> +})
Here as well, it's lable and not link

2024-03-19 08:16 UTC, Jonath-z requested changes

2024-03-19 08:16 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  });
You already tested the items, I don't think you need to test the empty items case

2024-03-19 08:16 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +    expect(link.children[0].className).toContain("activable-link");
Still have this

2024-03-19 08:16 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/LinkAction.test.tsx
> +});
Can check that the number of subItems is rendered as the same number of component

2024-03-19 08:16 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/index.test.tsx
> +});
you can also check the items number that are in the mock

2024-03-28 07:28 UTC, serapieTuyishime commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  it("should call goToLink function when clicked", () => {
```suggestion
  it("should invoke goToLink function when clicked", () => {
```

2024-04-03 07:43 UTC, Jonath-z approved these changes

2024-04-04 11:59 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  });
The test description does not explain the code tested here,  would you check this again?

2024-04-04 11:59 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  it("should invoke goToLink function when clicked", () => {
```suggestion
  it("should redirect to link when clicked", () => {
```

2024-04-04 11:59 UTC, Jonath-z commented on src/config/firebase.ts
> +    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || "mock-measurement",
```suggestion
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? " ",
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? " ",
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? " ",
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? " ",
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID ?? " ",
```

2024-05-06 09:21 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  });
Would you test with many subitems as well?

2024-05-06 09:21 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  });
how does this attest the the link is active?

2024-05-06 09:21 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  it("should redirect to link when clicked", () => {
```suggestion
  it("should invok goToLink when clicked", () => {
```

2024-05-08 08:26 UTC, Jonath-z reviewed
You can test the LinkAction component the same way you tested the ActivableLink component as they have the same structure and same logic

2024-05-08 08:26 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +  it("should render the link with many subitems", () => {
```suggestion
  it("should render the link when subitems are provided", () => {
```

2024-05-08 08:26 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/_partials/Action.test.tsx
> +    };
You can make this one mock with items, no need to separate them

2024-05-10 11:50 UTC, Jonath-z commented on __tests__/components/ui/SideNavigation/index.test.tsx
There still some points to test in this component, for example the menu title  when it's hidden or it's not, we need to test the case where we don't have any item passed, or we have the item but not the subItem

2024-05-10 15:23 UTC, merged