Fix/attach locale on all requests
dacadeorg/dacade-frontend-app pull request #1172
Opened 2024-03-13 14:46 UTC by serapieTuyishime

# Submit a pull request

- [ ] This is not a duplicate of an existing pull request.
- [ ] No existing features have been broken without good reason.
- [ ] Your commit messages are detailed
- [ ] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

Provide details about your pull request and what it adds, fixes, or changes.

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

:question:

## Issues Fixed

Enter the issue numbers resolved by this pull request below, if any.

1. :question:

## Other Relevant Information

Provide any other important details below.

2024-03-15 13:30 UTC, Samantha-KY approved these changes

2024-03-18 07:20 UTC, musayann approved these changes

2024-03-18 07:26 UTC, musayann requested changes
The learning related contents are not fetched in a translated.

In the sidenavigation:
<img width="339" alt="Screenshot 2024-03-18 at 10 24 47" src="https://github.com/dacadeorg/dacade-frontend-app/assets/29999003/c440cef3-9979-4aa8-b42d-c4549e03b41f">

In the challenge summary page:
<img width="1006" alt="Screenshot 2024-03-18 at 10 24 36" src="https://github.com/dacadeorg/dacade-frontend-app/assets/29999003/31edba71-7ed6-4d3a-8644-c48eb045ea1e">

2024-03-19 08:58 UTC, musayann requested changes
On the challenge overview the content is not translated

<img width="872" alt="Screenshot 2024-03-19 at 11 57 31" src="https://github.com/dacadeorg/dacade-frontend-app/assets/29999003/247e3c1e-10bb-4136-85f9-1bbde3156e5a">

2024-03-19 11:40 UTC, merged