Ft/learning materials page
dacadeorg/dacade-frontend-app pull request #1259
Opened 2024-05-31 08:19 UTC by serapieTuyishime

# Submit a pull request

- [ ] This is not a duplicate of an existing pull request.
- [ ] No existing features have been broken without good reason.
- [ ] Your commit messages are detailed
- [ ] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

This aims to create the new learning materials page on the community

:question:

## Breaking Changes

Describe what features are broken by this pull request and why, if any.

## Issues Fixed

Closes #1227

2024-06-04 15:13 UTC, mhenriette requested changes

2024-06-04 15:13 UTC, mhenriette commented on src/components/sections/communities/overview/Sidebar.tsx
>    const mainLink = hasCurrentCommunity ? `/communities/${currentCommunity.slug}` : "";
consider optimizing these links by using a `useMemo` hook
```suggestion
  const links = useMemo(() => {
    if (!hasCurrentCommunity)
      return {
        scoreboardLink: "",
        learningMaterialsLink: "",
        mainLink: "",
      };
    const { slug } = currentCommunity;
    return {
      scoreboardLink: `/communities/${slug}/scoreboard`,
      learningMaterialsLink: `/communities/${slug}/learning-materials`,
      mainLink: `/communities/${slug}`,
    };
  }, [hasCurrentCommunity, currentCommunity]);
```

2024-06-04 15:16 UTC, mhenriette reviewed
the pages looks good but I left few comments , consider implementing the reviews from @coderabbit as well.

The level label is missing
The course duration is missing 

also the alignment in the box is not consistent 
![Screenshot 2024-06-04 at 4 47 08 PM](https://github.com/dacadeorg/dacade-frontend-app/assets/98765148/aed09a99-e6f8-410b-9dcb-1bf45b34dda3)

2024-06-24 11:42 UTC, Samantha-KY approved these changes

2024-06-28 07:09 UTC, mhenriette approved these changes

2024-06-28 11:25 UTC, musayann approved these changes

2024-06-28 11:25 UTC, musayann commented on src/pages/communities/[slug]/index.tsx
> +        {getMetadataDescription(community?.description as string).map((attributes) => (
can you use the component the metadata component here

2024-06-28 11:25 UTC, musayann commented on src/pages/communities/[slug]/index.tsx
> +        <title>{getMetadataTitle(t("communities.navigation.courses"), community?.name as string)}</title>
can you make the page title as a component which will then handle everything within itself

2024-07-26 12:23 UTC, igorntwari reviewed
**Q and A**

- [x] The challenge text is quite small compared to what we have on the Figma design 
- [x] The leaning material title is smaller than what we have on the Figma design 
- [x] The score-board title is bigger than what we have on the Figma design 
- [x] The responsiveness of the challenge button is breaking on medium screen   
![image](https://github.com/user-attachments/assets/5790b297-b05a-420b-91c0-8fccd3475893)
- [ ] The gap between the button description and the arrow icon is quite big on medium screens and smartphones as well 
![image](https://github.com/user-attachments/assets/aa921697-1368-417a-89e9-92054924e020)
- [ ] The Submissions and Feedback on the small screens are flexed rows but on the design, they are flexed on the row 
![image](https://github.com/user-attachments/assets/4a55e1bc-b05e-42d5-9991-df7d45319e8d)

2024-08-22 11:17 UTC, musayann approved these changes

2024-08-22 11:17 UTC, merged