feat: add course card design
dacadeorg/dacade-frontend-app pull request #1270
Opened 2024-06-14 14:45 UTC by mhenriette

# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

## Pull Request Details

Implementing new design of course card

## Breaking Changes
none

## Issues Fixed
#1230 

## Other Relevant Information

2024-06-18 16:43 UTC, serapieTuyishime requested changes
There are couple UI comments.

* The items are not centerly aligned:
![image](https://github.com/dacadeorg/dacade-frontend-app/assets/70019756/7f03c0d2-cbb4-4e1f-898e-224392052d1a)
* between the "course" and the title, there should be 24px, but we have 30px - all horizontal gaps are 24px
* you forgot the dotted line above the button.

2024-06-18 16:43 UTC, serapieTuyishime commented on src/components/cards/CourseCard.tsx
the filename should be "Course.tsx", as there is no need to add "card" because we are in the cards folder.

2024-06-18 16:43 UTC, serapieTuyishime commented on src/components/cards/CourseCard.tsx
> +            } included`}</p>
Could you translate this!
And the word "single" is missing, it should be "3 Single learning modules included"

2024-06-18 16:43 UTC, serapieTuyishime commented on src/components/cards/challenge/Challenge.tsx
> +import Badges from "../../badges/Badges";
If possible, could we rename the component "index", so that we don't have "badges/badges"

2024-06-18 16:43 UTC, serapieTuyishime commented on src/styles/globals.css
> +.clip-polygon {
```suggestion
.clip-hexagon {
```

2024-06-19 15:43 UTC, mhenriette commented
> There are couple UI comments.
> 
> * The items are not centerly aligned:
>   ![image](https://private-user-images.githubusercontent.com/70019756/340760303-7f03c0d2-cbb4-4e1f-898e-224392052d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI5MjUsIm5iZiI6MTcxODgwMjYyNSwicGF0aCI6Ii83MDAxOTc1Ni8zNDA3NjAzMDMtN2YwM2MwZDItY2JiNC00ZTFmLTg5OGUtMjI0MzkyMDUyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MzQ1YzliZDI3ZDI1ZmQ2NWExM2IzOWUzZDczZjEzY2Q5ZDEwMjE0NzU0NTA0MDJhZDQ5OGQ5MDI2NzcxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XREwycTwXXOCAl-w4GT9z1RR8cbIcSJ6bkKHcTBw7rg)
> * between the "course" and the title, there should be 24px, but we have 30px - all horizontal gaps are 24px
> * you forgot the dotted line above the button.


about the spacing, it is already 24px 
![Screenshot 2024-06-19 at 10 24 20 AM](https://github.com/dacadeorg/dacade-frontend-app/assets/98765148/12828d47-0835-4374-b95a-a1213bcb0fe1)
and the dotted border appears when we have learning materials which in this case we don't because we don't have them on dev
![Screenshot 2024-06-19 at 5 43 21 PM](https://github.com/dacadeorg/dacade-frontend-app/assets/98765148/c1eb2ed2-7119-426b-9483-fa0180c88330)

2024-06-20 13:03 UTC, serapieTuyishime approved these changes

2024-06-24 10:52 UTC, Samantha-KY approved these changes

2024-06-26 07:55 UTC, Jonath-z commented on src/components/badges/DurationBadge.tsx
> +}
Is the useMemo really needed here?

```suggestion
  return (
    <div
      className={classNames("text-xxs uppercase font-semibold px-2 rounded-3xl inline-block text-gray-500 text-nowrap", {
        "bg-gray-200": type === "gray",
        "border border-gray-200": type === "bordered",
      })}
    >
      {getDuration(value, router.locale as string)}
    </div>
  );
}
```

2024-06-27 07:30 UTC, Jonath-z approved these changes

2024-06-28 11:38 UTC, musayann requested changes

2024-06-28 11:38 UTC, musayann commented on src/components/badges/index.tsx
>    useEffect(() => {
use a useMemo instead

2024-06-28 11:38 UTC, musayann commented on src/components/badges/index.tsx
> +  const level = challenge?.level || courseLevel;
you can not use a normal property as a dependency

2024-06-28 11:38 UTC, musayann commented on src/components/badges/index.tsx
>    useEffect(() => {
This is a suggestion of using it.

```ts
const level = useMemo(()=> {
     const value = challenge?.level || courseLevel;
     if (value === 0 || value === 1) return "course.challenge.level-0";
     return "course.challenge.level-2"
 }, [challenge?.level, courseLevel]);

2024-07-10 11:46 UTC, serapieTuyishime approved these changes

2024-07-23 11:37 UTC, musayann approved these changes

2024-07-23 11:37 UTC, merged